services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    Lle\DashboardBundle\Controller\:
        resource: '../../Controller'

    Lle\DashboardBundle\Widgets\:
        resource: '../../Widgets'
        tags: ['lle_dashboard.widget']

    Lle\DashboardBundle\Repository\:
        resource: '../../Repository/*'

    Lle\DashboardBundle\Service\WidgetProvider:
        class: Lle\DashboardBundle\Service\WidgetProvider
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - [!tagged lle_dashboard.widget]

    Lle\DashboardBundle\Maker\MakeWidget:
        tags: [maker.command]

    Lle\DashboardBundle\Widgets\AbstractWidget:
        calls:
            - setSecurity: ['@security.authorization_checker']
